[package]
name = "weber"
version = "0.1.0"
edition = "2021"
authors = ["Blinc <https://github.com/Blinc13>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threads_pool = "0.2.6"
httparse = "1.7.1"
buffer = "0.1.9"
http = "0.2.8"